import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
// fonts import
import {Inter} from 'next/font/google'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// font configuration
const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
